import streamlit as st
import time
import logging
import datetime
from services.persistence.exercise_repository import save_exercise, get_or_create_user, update_user_streaks, get_users_exercises
from services.coaching.form_analyzer import calculate_form_score
from services.tracking.progress_analytics import calculate_streaks
from services.tracking.calorie_estimator import estimate_calories_from_time

def sync_metrics_update(context):
    # If the WebRTC stream has not started or has stopped, do nothing
    if not context or not context.video_processor:
        return
    
    processor = context.video_processor
    
    # 0. Check if a session reset is requested (e.g. from starting a new workout)
    if st.session_state.get("needs_reset", False):
        processor.reps = 0
        processor.current_set_reps = 0
        processor.sets_completed = 0
        processor.stage = None
        processor.form_feedback = None
        processor.depth_status = "Unknown"
        processor.body_alignment = "Unknown"
        processor.hip_status = "Unknown"
        processor.shoulder_status = "Unknown"
        processor.swing_status = "Unknown"
        processor.extension_status = "Unknown"
        processor.back_arch_status = "Unknown"
        processor.balance_status = "Unknown"
        # Also reset the active detector so its internal rep/stage state is cleared
        if processor._detector is not None:
            processor._detector.reset()
        st.session_state.last_announced_rep = 0
        st.session_state.last_rep_count = 0
        st.session_state.form_score = 100
        st.session_state.strongest_area = "N/A"
        st.session_state.weakest_area = "N/A"
        st.session_state.average_form_score = 0.0
        st.session_state.best_form_score = 0.0
        st.session_state.form_scores_history = []
        st.session_state.component_sums = {}
        st.session_state.component_counts = {}
        st.session_state.last_score_update_time = time.time()
        st.session_state.last_score_voice_time = time.time()
        st.session_state.needs_reset = False
    
    # 1. Push configurations down to the video processor (main thread -> processing thread)
    processor.exercise_type = st.session_state.get("exercise_type", "Squats")
    processor.target_sets = st.session_state.get("target_sets", 0)
    processor.reps_per_set = st.session_state.get("reps_per_set", 0)
    
    # Push voice coaching properties down to the background processing thread
    processor.voice_pipeline = st.session_state.get("voice_pipeline")
    processor.voice_enabled = st.session_state.get("voice_enabled", True)
    processor.voice_volume = st.session_state.get("voice_volume", 1.0)
    processor.voice_gender = st.session_state.get("voice_gender", "Female")
    processor.voice_engine = st.session_state.get("voice_engine", "pyttsx3 / gTTS")
    processor.voice_event_bus = st.session_state.get("voice_event_bus")
    
    # 2. Pull metrics from the video processor (processing thread -> main thread)
    st.session_state.reps = processor.reps
    st.session_state.current_set_reps = processor.current_set_reps
    st.session_state.sets_completed = processor.sets_completed
    
    # Pull pending browser speech cues generated by the background thread
    if getattr(processor, "pending_browser_speech", None):
        st.session_state.browser_speech = processor.pending_browser_speech
        processor.pending_browser_speech = None
    
    # Exercise specific metrics pulling
    st.session_state.knee_angle = getattr(processor, "knee_angle", 0)
    st.session_state.back_angle = getattr(processor, "back_angle", 0)
    st.session_state.depth_status = getattr(processor, "depth_status", "Unknown")
    st.session_state.elbow_angle = getattr(processor, "elbow_angle", 0)
    st.session_state.body_alignment = getattr(processor, "body_alignment", "Unknown")
    st.session_state.hip_status = getattr(processor, "hip_status", "Unknown")
    st.session_state.shoulder_status = getattr(processor, "shoulder_status", "Unknown")
    st.session_state.swing_status = getattr(processor, "swing_status", "Unknown")
    st.session_state.extension_status = getattr(processor, "extension_status", "Unknown")
    st.session_state.back_arch_status = getattr(processor, "back_arch_status", "Unknown")
    st.session_state.front_knee_angle = getattr(processor, "front_knee_angle", 0)
    st.session_state.torso_angle = getattr(processor, "torso_angle", 0)
    st.session_state.balance_status = getattr(processor, "balance_status", "Unknown")
    
    # Bilateral angles
    st.session_state.left_elbow_angle = getattr(processor, "left_elbow_angle", 0)
    st.session_state.right_elbow_angle = getattr(processor, "right_elbow_angle", 0)
    st.session_state.left_knee_angle = getattr(processor, "left_knee_angle", 0)
    st.session_state.right_knee_angle = getattr(processor, "right_knee_angle", 0)
    
    # Define a common payload of current metrics to share with the voice pipeline
    current_completed = st.session_state.sets_completed
    current_metrics = {
        "knee_angle": st.session_state.knee_angle,
        "back_angle": st.session_state.back_angle,
        "depth_status": st.session_state.depth_status,
        "elbow_angle": st.session_state.elbow_angle,
        "body_alignment": st.session_state.body_alignment,
        "hip_status": st.session_state.hip_status,
        "shoulder_status": st.session_state.shoulder_status,
        "swing_status": st.session_state.swing_status,
        "extension_status": st.session_state.extension_status,
        "back_arch_status": st.session_state.back_arch_status,
        "front_knee_angle": st.session_state.front_knee_angle,
        "torso_angle": st.session_state.torso_angle,
        "balance_status": st.session_state.balance_status,
        "reps": st.session_state.reps,
        "current_set_reps": st.session_state.current_set_reps,
        "sets_completed": current_completed,
        "target_sets": st.session_state.target_sets,
        "reps_per_set": st.session_state.reps_per_set,
    }
    
    # Calculate form score once per second during the workout
    if st.session_state.get("workout_started", False):
        now = time.time()
        last_update = st.session_state.get("last_score_update_time", 0.0)
        
        # Check if a second has passed
        if now - last_update >= 1.0:
            score, components = calculate_form_score(st.session_state.exercise_type, current_metrics)
            st.session_state.form_score = score
            
            # Determine strongest and weakest component in the current frame
            if components:
                sorted_comps = sorted(components.items(), key=lambda x: x[1])
                st.session_state.weakest_area = sorted_comps[0][0]
                st.session_state.strongest_area = sorted_comps[-1][0]
                
            # Only record running averages and history when actively exercising
            from services.coaching.form_analyzer import is_active_exercise_frame
            if is_active_exercise_frame(st.session_state.exercise_type, current_metrics):
                if components:
                    sums = st.session_state.get("component_sums", {})
                    counts = st.session_state.get("component_counts", {})
                    for k, val in components.items():
                        sums[k] = sums.get(k, 0.0) + val
                        counts[k] = counts.get(k, 0) + 1
                    st.session_state.component_sums = sums
                    st.session_state.component_counts = counts
                    
                # Update history
                history = st.session_state.get("form_scores_history", [])
                history.append(score)
                st.session_state.form_scores_history = history
                
                # Calculate running average and best score
                st.session_state.average_form_score = sum(history) / len(history) if history else 0.0
                st.session_state.best_form_score = max(st.session_state.best_form_score, score)
            
            st.session_state.last_score_update_time = now

        # Voice coaching trigger based on Form Score category
        last_score_voice = st.session_state.get("last_score_voice_time", 0.0)
        if now - last_score_voice >= 8.0:
            cur_score = st.session_state.get("form_score", 100)
            voice_text = ""
            if cur_score > 90:
                voice_text = "Excellent form!"
            elif 75 <= cur_score <= 90:
                voice_text = "Good form. Keep going."
            elif cur_score < 60:
                voice_text = "Focus on your posture."
                
            if voice_text and st.session_state.get("voice_pipeline"):
                st.session_state.voice_pipeline.speak(voice_text, priority="normal")
                st.session_state.last_score_voice_time = now

    # 3. Handle database saving when a set is completed
    last_saved = st.session_state.get("last_saved_sets_completed", 0)
    
    if current_completed > last_saved:
        time_taken = time.time() - st.session_state.get("set_cycle_started_at", time.time())
        try:
            # 1. Fetch previous user details to check last workout date
            prev_profile = get_or_create_user(st.session_state.username)
            last_date_str = prev_profile.get("last_workout_date") if prev_profile else None
            today_str = datetime.date.today().strftime("%Y-%m-%d")
            
            # Fetch history rows to check improvement
            history_rows = get_users_exercises(st.session_state.user_id)
            
            # Current session metrics (computed at set completion)
            current_session_metrics = {
                "average_form_score": st.session_state.get("average_form_score", 0.0),
                "best_form_score": st.session_state.get("best_form_score", 0.0),
                "total_reps": st.session_state.reps,
                "total_sets": current_completed,
                "component_sums": st.session_state.get("component_sums", {}),
                "component_counts": st.session_state.get("component_counts", {})
            }
            
            curr_streak = prev_profile.get("current_streak", 0) if prev_profile else 0
            longest_streak = prev_profile.get("longest_streak", 0) if prev_profile else 0
            user_streaks = {"current_streak": curr_streak, "longest_streak": longest_streak}
            
            llm_coach = None
            if st.session_state.get("voice_pipeline") and hasattr(st.session_state.voice_pipeline, "llm"):
                llm_coach = st.session_state.voice_pipeline.llm
                
            from services.coaching.feedback_manager import generate_personalized_feedback
            feedback = generate_personalized_feedback(
                exercise_type=st.session_state.exercise_type,
                current_session_metrics=current_session_metrics,
                history_rows=history_rows,
                user_streaks=user_streaks,
                llm_coach=llm_coach
            )
            
            st.session_state.overall_rating = feedback["rating"]
            st.session_state.strongest_area = feedback["strongest_area"]
            st.session_state.weakest_area = feedback["weakest_area"]
            st.session_state.improvement_percentage = feedback["improvement_percentage"]
            st.session_state.feedback_summary = feedback["feedback_summary"]
            st.session_state.recommendation = feedback["recommendation"]
            
            # 2. Save exercise set to DB
            save_exercise(
                user_id=st.session_state.user_id,
                exercise_name=st.session_state.exercise_type,
                reps=st.session_state.reps_per_set,
                sets=1,
                time_spent=time_taken,
                average_form_score=st.session_state.get("average_form_score", 0.0),
                best_form_score=st.session_state.get("best_form_score", 0.0),
                feedback_summary=feedback["feedback_summary"],
                strongest_area=feedback["strongest_area"],
                weakest_area=feedback["weakest_area"],
                improvement_percentage=feedback["improvement_percentage"]
            )
            
            # 3. Calculate new streaks
            history_rows_updated = get_users_exercises(st.session_state.user_id)
            dates = [row['created_at'] for row in history_rows_updated]
            new_curr, new_long, new_active, _ = calculate_streaks(dates)
            
            # 4. Check if a new milestone is achieved on their first workout today
            if last_date_str != today_str:
                milestones = {
                    3: "Congratulations! 3 day workout streak achieved. Great start! Keep your streak alive.",
                    7: "Congratulations! 7 day workout streak achieved. One week strong! Excellent consistency.",
                    14: "Congratulations! 14 day workout streak achieved. Two weeks strong! Keep up the momentum.",
                    30: "Congratulations! 30 day workout streak achieved. Outstanding! You have built a powerful habit.",
                    100: "Congratulations! 100 day workout streak achieved. Elite consistency! You are unstoppable."
                }
                if new_curr in milestones:
                    msg = milestones[new_curr]
                    if st.session_state.get("voice_pipeline"):
                        st.session_state.voice_pipeline.speak(msg, priority="high")
            
            # 5. Update user streaks in DB
            update_user_streaks(st.session_state.user_id, new_curr, new_long, today_str)
            
        except Exception as e:
            logging.error(f"Failed to save exercise set and update streaks: {e}")
            
        st.session_state.last_saved_sets_completed = current_completed
        st.session_state.set_cycle_started_at = time.time()
        
    # 4. Voice coaching triggering on Set Completion
    last_notified_sets = st.session_state.get("last_notified_sets_completed", 0)
    if current_completed > last_notified_sets:
        rest_secs = st.session_state.get("rest_duration", 60)

        # ── Publish rest_timer_start event (voice + timer) ────────────────────
        if st.session_state.get("voice_event_bus"):
            st.session_state.voice_event_bus.publish(
                "rest_timer_start",
                {"rest_seconds": rest_secs, "set_num": current_completed}
            )

        # ── Start rest countdown timer in session state ───────────────────────
        st.session_state.rest_timer_active = True
        st.session_state.rest_timer_end = time.time() + rest_secs
        st.session_state.last_rest_countdown_spoken = -1

        if st.session_state.get("voice_pipeline"):
            try:
                result = st.session_state.voice_pipeline.process_event(
                    event="set_completed",
                    exercise=st.session_state.exercise_type,
                    metrics=current_metrics
                )
                if result:
                    st.session_state.audio_to_play, st.session_state.coach_feedback, st.session_state.audio_duration = result
                    st.session_state.audio_play_start = time.time()
            except Exception as e:
                logging.error(f"Error triggering set completion coaching: {e}")

        st.session_state.last_notified_sets_completed = current_completed

    # 4b. ── Rest Timer Countdown Voice Cues ──────────────────────────────────
    if st.session_state.get("rest_timer_active", False):
        remaining = st.session_state.rest_timer_end - time.time()
        if remaining <= 0:
            # Timer finished — clear it and nudge the user to start
            st.session_state.rest_timer_active = False
            if st.session_state.get("voice_pipeline"):
                st.session_state.voice_pipeline.speak("Rest complete! Start your next set.", priority="high")
        else:
            last_spoken = st.session_state.get("last_rest_countdown_spoken", -1)
            rem_int = int(remaining)
            # Announce at 30s, 10s, 5s, 3s, 2s, 1s milestones
            for milestone in [30, 10, 5, 3, 2, 1]:
                if rem_int == milestone and last_spoken != milestone:
                    if st.session_state.get("voice_pipeline"):
                        if milestone <= 3:
                            st.session_state.voice_pipeline.speak(str(milestone), priority="high")
                        else:
                            st.session_state.voice_pipeline.speak(f"{milestone} seconds remaining.", priority="normal")
                    st.session_state.last_rest_countdown_spoken = milestone
                    break

    # 4c. ── Sync injury_warning_active from processor ─────────────────────────
    if context.video_processor is not None:
        proc = context.video_processor
        consecutive_bad = getattr(proc, "consecutive_bad_reps", 0)
        if consecutive_bad >= 3:
            st.session_state.injury_warning_active = True
            st.session_state.injury_warning_shown_at = time.time()
        elif st.session_state.get("injury_warning_active", False):
            # Auto-clear warning after 8 seconds of good form
            if time.time() - st.session_state.get("injury_warning_shown_at", 0) > 8.0:
                st.session_state.injury_warning_active = False

    # 5. Voice coaching triggering on Workout Completion
    target_sets = st.session_state.get("target_sets", 0)
    is_workout_complete = current_completed >= target_sets and target_sets > 0
    last_notified_complete = st.session_state.get("last_notified_workout_complete", False)
    
    if is_workout_complete and not last_notified_complete:
        if st.session_state.get("voice_pipeline"):
            try:
                from services.coaching.feedback_manager import finalize_workout_feedback
                feedback = finalize_workout_feedback()
                voice_cue = feedback.get("voice_cue", "Excellent work today. Workout completed.")
                
                result = st.session_state.voice_pipeline.speak(voice_cue, priority="high")
                if result:
                    st.session_state.audio_to_play, st.session_state.coach_feedback, st.session_state.audio_duration = result
                    st.session_state.audio_play_start = time.time()
            except Exception as e:
                logging.error(f"Error triggering workout completion coaching: {e}")
                
        st.session_state.last_notified_workout_complete = True

    # 6. Consume events from the Voice Event Bus
    bus = st.session_state.get("voice_event_bus")
    pipeline = st.session_state.get("voice_pipeline")
    if bus and pipeline:
        events = bus.consume_all()
        if events:
            logging.info(f"[MetricsSync] Consumed {len(events)} events from VoiceEventBus.")
        for event_type, payload in events:
            try:
                logging.info(f"[MetricsSync] Passing event '{event_type}' with payload {payload} to pipeline.consume_event()")
                result = pipeline.consume_event(event_type, payload)
                if result:
                    audio_bytes, txt, dur = result
                    logging.info(f"[MetricsSync] consume_event returned valid audio: size={len(audio_bytes) if audio_bytes else 0} bytes")
                    st.session_state.audio_to_play, st.session_state.coach_feedback, st.session_state.audio_duration = result
                    st.session_state.audio_play_start = time.time()
            except Exception as e:
                logging.error(f"Error consuming event {event_type} from bus: {e}", exc_info=True)

    # 7. ── Live Calorie Estimator ────────────────────────────────────────
    if st.session_state.get("workout_started", False):
        workout_start = st.session_state.get("workout_start_time", 0.0)
        if workout_start > 0:
            elapsed = time.time() - workout_start
            exercise = st.session_state.get("exercise_type", "Squats")
            weight_kg = st.session_state.get("body_weight_kg", 70.0)
            kcal = estimate_calories_from_time(exercise, elapsed, weight_kg)
            st.session_state.calories_burned = kcal

    # 8. ── Program Auto-Transition ──────────────────────────────────────
    if st.session_state.get("program_mode", False):
        prog = st.session_state.get("active_program", [])
        idx = st.session_state.get("program_exercise_index", 0)
        target_sets = st.session_state.get("target_sets", 0)
        sets_done = st.session_state.get("sets_completed", 0)
        transitioning = st.session_state.get("program_transitioning", False)

        # When current exercise sets are complete, advance to next
        if sets_done >= target_sets > 0 and not transitioning and idx < len(prog):
            next_idx = idx + 1
            if next_idx < len(prog):
                # Schedule transition after 3 seconds (mid-rest)
                st.session_state.program_transitioning = True
                st.session_state.program_transition_at = time.time() + 3.0
                next_ex = prog[next_idx]
                if st.session_state.get("voice_pipeline"):
                    st.session_state.voice_pipeline.speak(
                        f"Exercise complete! Get ready for {next_ex['name']} in 3 seconds.",
                        priority="high"
                    )
            else:
                # All exercises in program done
                if not st.session_state.get("last_notified_workout_complete", False):
                    st.session_state.program_mode = False

        # Execute the transition
        if transitioning and time.time() >= st.session_state.get("program_transition_at", 0):
            next_idx = st.session_state.program_exercise_index + 1
            if next_idx < len(prog):
                next_ex = prog[next_idx]
                st.session_state.program_exercise_index = next_idx
                st.session_state.exercise_type = next_ex["name"]
                st.session_state.target_sets = next_ex["sets"]
                st.session_state.reps_per_set = next_ex["reps"]
                st.session_state.rest_duration = next_ex.get("rest_seconds", 60)
                # Reset per-exercise tracking
                st.session_state.sets_completed = 0
                st.session_state.last_saved_sets_completed = 0
                st.session_state.last_notified_sets_completed = 0
                st.session_state.reps = 0
                st.session_state.current_set_reps = 0
                st.session_state.form_scores_history = []
                st.session_state.average_form_score = 0.0
                st.session_state.best_form_score = 0.0
                st.session_state.component_sums = {}
                st.session_state.component_counts = {}
                st.session_state.rest_timer_active = False
                st.session_state.program_transitioning = False
                st.session_state.workout_start_time = time.time()
